sudo apt install python-certbot-apache
sudo apt install fail2ban
sudo apt install lynx
sudo apt install lynx6
sudo apt install www-browser
sudo apt install links2
sudo apt install golang
sudo apt instal gox
sudo apt install gox
sudo apt install sshpass
